image_root: './LOCAL_DATASET/blip/downstream/videodownstream/msrvtt_qa/videos'
ann_root: 'annotation'

train_ann: './LOCAL_DATASET/blip/downstream/videodownstream/data/msrvtt_qa/txt/new_train.json'
val_ann: './LOCAL_DATASET/blip/downstream/videodownstream/data/msrvtt_qa/txt/new_val.json'
test_ann: './LOCAL_DATASET/blip/downstream/videodownstream/data/msrvtt_qa/txt/new_test.json'
answer_list: './LOCAL_DATASET/blip/downstream/videodownstream/data/msrvtt_qa/txt/answer_list.json'

dataset: 'video_qa'

# set pretrained as a file path or an url
# pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'
pretrained: './OUTPUT/BLIP/BLIP_timesformer_epoch10_imgbs2880_vidbs640_lr7e-5_lrdecay0.85_web10m_generated/checkpoint_09.pth'
# size of vit model; base or large

task_type: 'video_qa'
encoder_name: 'timesformer'
share_weights: True
cls_on: True
inflate: False
batch_size_train: 1
batch_size_test: 4
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 5e-6
optim_step: 1

ensemble_n_clips: 1
input_length: 32
temporal_stride: 2
video_fmt: '.mp4'
image_size: 480

enable_mae: False
mask_ratio: 0.75
aux_mask_ratio: 0.75
mae_weight: 10.

k_test: 128
inference: 'rank'

# optimizer
weight_decay: 0.05
decay_pos: True
min_lr: 0
max_epoch: 10